// <auto-generated />
namespace MahotaApp.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FirstCommitDataModelForIventoryofToolingEquipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstCommitDataModelForIventoryofToolingEquipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201508111841556_First Commit Data Model For Iventory of Tooling Equipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
